name: Build test app

on:
  workflow_dispatch:
    inputs:
      buildType:
        type: choice
        description: 'Build Type'
        default: Release
        options: 
        - Dev
        - Pre-release
        - Release
      overwriteVersion:
        type: boolean
        default: false
        description: 'Overwrite CMakeLists.txt version'
      versionMajor:
        type: string
        description: 'Version major'
        default: '1'
      versionMinor:
        type: string
        description: 'Version minor'
        default: '0'
      versionPatch:
        type: string
        description: 'Version patch'
        default: '0'
      versionRev:
        type: string
        description: 'Version rev'
        default: '0'
      useSdkBuild:
        type: boolean
        default: false
        description: 'Use SDK build instead of SDKLIB repository'
      sdkBuild:
        type: string
        description: 'SDK build name (if empty latest build is used), list of names are available in Get SDK builds action'      
        

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  GITHUB_BUILD_NUMBER: ''
  USE_SDK_BUILD: ${{ github.event.inputs.useSdkBuild }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  MBS_PATH: "${{ github.workspace }}/TestApp"
  
jobs:
  build:
    runs-on: windows-2022

    steps:
     
    - uses: actions/checkout@v6.0.2

    - name: Get latest SDK Build
      if: ${{ github.event.inputs.sdkBuild == '' }}
      run: |
        $ARTIFACT = curl -sH "Authorization: token ${{ secrets.PAT }}" https://api.github.com/repos/ZePuMedical/imsonicSWUpgraded/actions/artifacts | jq -r '.artifacts[0].name'
        echo "Latest SDK Build: $ARTIFACT"
        echo "sdk_build_name=$ARTIFACT" >> $env:GITHUB_ENV

    - name: Set user defined SDK Build name
      if: ${{ github.event.inputs.sdkBuild != '' }}
      run: |
        echo "sdk_build_name=${{ github.event.inputs.sdkBuild }}" >> $env:GITHUB_ENV
        echo "branch: ${{ github.ref_name }}"
        
    - name: Download SDK Build
      uses: tomasbkk/actions-download-artifact@claude/crazy-ardinghelli
      if: ${{ github.event.inputs.useSdkBuild == 'true' || github.event.inputs.useSdkBuild == '' }}
      with:
        repo: ZepuMedical/imsonicSWUpgraded
        github_token: ${{ secrets.PAT }}
        name: ${{ github.event.inputs.sdkBuild }}
        latest: ${{ github.event.inputs.sdkBuild == '' }}
        
    - name: Install boost
      uses: tomasbkk/install-boost@v2.5.2
      id: install-boost
      with:
          # REQUIRED: Specify the required boost version
          # A list of supported versions can be found here:
          # https://github.com/MarkusJx/prebuilt-boost/blob/main/versions-manifest.json
          boost_version: 1.79.0
          # OPTIONAL: Specify a custon install location
          boost_install_dir: C:\local\boost_1_79_0
          # OPTIONAL: Specify a platform version
          platform_version: 2022
          # OPTIONAL: Specify a toolset
          toolset: msvc
          cache: true
          
    - name: Get timestamp
      if: true
      id: time
      uses: nanzm/get-time-action@v2.0
      with:
        format: 'YYYY.MM.DD-HH.mm.ss'
        
    - name: Get version
      if: true
      shell: cmd
      run: |
        cd ${{ env.MBS_PATH }}
        get_version.bat
              
    - name: Configure CMake
      if: true
      run: cmake -G "Visual Studio 17 2022" -S ${{ env.MBS_PATH }} -B ${{github.workspace}}/build

    - name: Build
      if: true
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{ env.BUILD_TYPE }}
     
    - name: Read version information
      if: true
      id: versionInfo
      uses: juliangruber/read-file-action@v1
      with:
        path: ${{ github.workspace }}\TestApp\version_formatted.txt
        
    - name: Trim version
      if: true
      id: versionTrim
      uses: tomasbkk/replace-string-action@v2.5.2
      with:
        pattern: '\\s+'
        string: ${{ steps.versionInfo.outputs.content }}
        replace-with: ''
        
    - name: Create build artifact
      if: true
      uses: actions/upload-artifact@v7.0.0
      with:
        name: Mt.TestApp${{ steps.versionTrim.outputs.replaced }}
        path: ${{ github.workspace }}\build\Release
        
    - name: Zip build outputs
      if: true
      uses: thedoctor0/zip-release@0.7.6
      with:
        path: '${{ github.workspace }}\build\Release\*'
        filename: 'TestApp${{ steps.versionTrim.outputs.replaced }}.${{ github.run_number }}.zip'
  
    - name: Zip symbols
      if: true
      uses: thedoctor0/zip-release@0.7.6
      with:
        path: '${{ github.workspace }}\build\Release\*'
        filename: 'Symbols${{ steps.versionTrim.outputs.replaced }}.${{ github.run_number }}.zip'
  
    - name: Create a GitHub release
      id: create_release
      uses: tomasbkk/action-automatic-releases@v1.2.2
      if: true
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: "${{ steps.versionTrim.outputs.replaced }}.${{ github.run_number }}"
        prerelease: ${{ contains(github.event.inputs.buildType, 'Pre-release') }}
        title: Release ${{ steps.tag_version.outputs.new_tag }}
        files: |
          TestApp${{ steps.versionTrim.outputs.replaced }}.${{ github.run_number }}.zip
          Symbols${{ steps.versionTrim.outputs.replaced }}.${{ github.run_number }}.zip
          
    - name: Create tag
      uses: tomasbkk/create-tag@v1.0.3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        version: '1.0.0.0_dev_144_2023.08.11-11.48.47'
        message: 'Release 1.0.0.0_dev_144_2023.08.11-11.48.47'
        semanticVersion: 'false'
        onTagExists: 'update'
          
    - name: Upload bundle
      if: true
      uses: tomasbkk/action-ftp-upload@v1.2.1
      with:
        user: "u836597012.imsonic"
        password: "ZepuZepu311"
        host: "tomasbkk.com"
        src: "TestApp${{ steps.versionTrim.outputs.replaced }}.${{ github.run_number }}.zip"
        dest: "newTestApp${{ steps.versionTrim.outputs.replaced }}.${{ github.run_number }}.zip"
