name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      buildType:
        type: choice
        description: 'Build Type'
        default: Release
        options: 
        - Dev
        - Pre-release
        - Release
      overwriteVersion:
        type: boolean
        default: false
        description: 'Overwrite CMakeLists.txt version'
      versionMajor:
        type: string
        description: 'Version major'
        default: '1'
      versionMinor:
        type: string
        description: 'Version minor'
        default: '0'
      versionPatch:
        type: string
        description: 'Version patch'
        default: '0'
        

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -G "Visual Studio 16 2019" -S ${{ github.workspace }}/TestApp -B ${{github.workspace}}/build

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{ env.BUILD_TYPE }}
     
    - name: Read version information
      id: versionInfo
      uses: juliangruber/read-file-action@v1
      with:
        path: ${{ github.workspace }}\TestApp\version.txt
        
    - name: Trim version
      id: versionTrim
      uses: frabert/replace-string-action@v2.0
      with:
        pattern: '\\s+'
        string: ${{ steps.versionInfo.outputs.content }}
        replace-with: ''
        
    - name: Set env
      run: echo "GITHUB_BUILD_NUMBER=${{ steps.versionTrim.outputs.replaced }}" >> $GITHUB_ENV
    - name: Test
      run: echo $GITHUB_BUILD_NUMBER
      
    - name: Zip build outputs
      uses: thedoctor0/zip-release@main
      with:
        path: '${{ github.workspace }}\build\Release\*'
        filename: 'TestApp${{ steps.versionTrim.outputs.replaced }}.${{ github.run_number }}.zip'
  
    - name: Create a GitHub release
      id: create_release
      uses: "marvinpinto/action-automatic-releases@v1.2.1"
      if: ${{ github.event.inputs.buildType == 'Pre-release' || github.event.inputs.buildType == 'Release' }}
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: "${{ steps.versionTrim.outputs.replaced }}.${{ github.run_number }}"
        prerelease: ${{ contains(github.event.inputs.buildType, 'Pre-release') }}
        title: Release ${{ steps.tag_version.outputs.new_tag }}
        files: 'TestApp${{ steps.versionTrim.outputs.replaced }}.${{ github.run_number }}.zip'         

