name: Download Artifact

on:
  workflow_dispatch:
    inputs:
      artifact_name:
        description: 'The name of the artifact to download. Leave blank to download the latest artifact.'
        required: false

jobs:
  download:
    runs-on: windows-2019
    steps:
      - name: Download Artifact
        uses: aochmann/actions-download-artifact@1.0.4
        with:
          repo: ZepuMedical/imsonicSWUpgraded
          github_token: ${{ secrets.PAT }}
          name: ${{ github.event.inputs.artifact_name }}
          latest: ${{ github.event.inputs.artifact_name == '' }}
          path: ImSonicSDK
          

      - name: Use Downloaded Artifact
        run: |
          # Do something with the downloaded artifact
          dir
          cd ${{ github.event.inputs.artifact_name }}
          dir
          cd bin
          dir


