name: Download Artifact

on:
  workflow_dispatch:
    inputs:
      artifact_name:
        description: 'The name of the artifact to download. Leave blank to download the latest artifact.'
        required: false

jobs:
  download:
    runs-on: windows-2019
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          repository: ZepuMedical/imsonicSWUpgraded
          token: ${{ secrets.PAT }}
          name: ${{ github.event.inputs.artifact_name || 'latest' }}
          path: .

      - name: Use Downloaded Artifact
        run: |
          # Do something with the downloaded artifact
          dir .
