name: Download artifact

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-2019

    steps:
    
    - name: Download SDK Build
      uses: tomasbkk/actions-download-artifact@master
      with:
        repo: ZepuMedical/imsonicSWUpgraded
        github_token: ${{ secrets.PAT }}
        name: ImSonicSDK_1.0.0.0_dev_114_2023.03.21-11.34.46
        latest: false
        path: ImSonicSDK
