name: Get release notes
on:
  workflow_dispatch:

jobs:
  get-release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Release Notes
        id: notes
        uses: tomasbkk/release-notes-action@add_previous_tag
        with:
          owner: 'ImSonicZePu'
          repo: 'MtBakerSystem'
          tag-name: '1.0.0.0_dev_144_2023.08.11-11.48.47'
          token: ${{ secrets.PAT }}
          branch: 'master'
      - name: Do something
        run: echo ${{ steps.notes.outputs.release-notes }}          
