name: Get Tags
on:
  workflow_dispatch:

jobs:
  gettags:
    runs-on: windows-latest  # Use Windows Server 2019

    steps:
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Use the desired Python version

    - name: Install dependencies
      run: pip install requests

    - name: Run Python script
      run: python TestApp/get_last_tags.py  # Replace with the actual script filename


      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
