name: Get release notes
on:
  workflow_dispatch:

jobs:
  list-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: get release notes
        run: |
          OWNER="ImSonicZePu"
          REPO="MtBakerSystem"
          TOKEN="${{ secrets.PAT }}"
          ARTIFACTS=$(curl -sH "Authorization: token ${TOKEN}" \
              "https://api.github.com/repos/${OWNER}/${REPO}/releases/generate-notes?tag_name=v0.9.2.3_dev_2023.09.08-10.35.17" \
              | jq -r '.artifacts[] | "Name: \(.name)\nSize: \(.size_in_bytes)\nExpires: \(.expires_at)\nBuilt on branch: \(.workflow_run.head_branch)\n"')
          echo -e "Release notes:\n\n$ARTIFACTS"
