name: Advance get artifacts
on: [workflow_dispatch]
jobs:
  get-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: List Artifacts
        run: |
          OWNER="ZePuMedical"
          REPO="imsonicSWUpgraded"
          TOKEN="${{ secrets.PAT }}"
          PAGE=1
          while true; do
            ARTIFACTS=$(curl -sH "Authorization: token ${TOKEN}" \
              "https://api.github.com/repos/${OWNER}/${REPO}/actions/artifacts?per_page=100&page=${PAGE}" \
              | jq -r '.artifacts[].url')
            if [ -z "$ARTIFACTS" ]; then
              break
            fi
            echo "Artifacts: $ARTIFACTS"
            PAGE=$((PAGE+1))
          done
