name: Get artifact name
on:
  workflow_dispatch:

jobs:
  get_artifact_name:
    runs-on: windows-2019
    steps:
      - name: Get latest artifact name
        run: |
          $ARTIFACT = curl -sH "Authorization: token ${{ secrets.PAT }}" https://api.github.com/repos/ZePuMedical/imsonicSWUpgraded/actions/artifacts | jq -r '.artifacts[0].name'
          echo "Latest artifact name: $ARTIFACT"
          echo "sdk_build_name=$ARTIFACT" >> $env:GITHUB_ENV
          
      - name: list dir
        run: |
          dir .
