name: Update Artifacts List
on:
  repository_dispatch:
    types: [ "update-artifacts" ]
  workflow_dispatch:

jobs:
  update-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: List Artifacts
        id: list-artifacts
        run: |
          OWNER="ZePuMedical"
          REPO="imsonicSWUpgraded"
          TOKEN="${{ secrets.PAT }}"
          curl -sH "Authorization: token ${TOKEN}" \
            "https://api.github.com/repos/${OWNER}/${REPO}/actions/artifacts?per_page=100" \
            -o artifacts.json

          ARTIFACTS=$(jq -c '[.artifacts[] | {name: .name, id: .id}]' artifacts.json)
          echo "$ARTIFACTS" > artifacts-list.json

          curl -X POST \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"event_type": "update-artifacts"}' \
            "https://api.github.com/repos/${OWNER}/${REPO}/dispatches"
