name: Get release notes
on:
  workflow_dispatch:

jobs:
  get-release-notes:
    runs-on: windows-latest
    steps:
      - name: Checkout Mt.BakerSystem
        uses: actions/checkout@v3
        with:
          fetch-tags: 'true'
        
      - name: Generate Release Notes
        id: notes
        uses: RedCrafter07/release-notes-action@v1
        with:
          tag-name: ${{ github.ref-name }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Do something
        run: echo ${{ steps.notes.outputs.release-notes }}
