name: Get release notes
on:
  workflow_dispatch:

jobs:
  get-release-notes:
    runs-on: windows-latest
    steps:
      - name: Checkout Mt.BakerSystem
        uses: actions/checkout@v3

      - name: Get last 2 repo tags
        shell: cmd
        run: |
          git --status
          ${{ github.workspace }}/TestApp/get_git_tags.bat
      
      - name: Generate Release Notes
        id: notes
        uses: tomasbkk/release-notes-action@add_previous_tag
        with:
          tag-name: ${{ env.REPO_TAG1 }}
          prev-tag-name: ${{ env.REPO_TAG2 }}
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'master'
      - name: Do something
        run: echo ${{ steps.notes.outputs.release-notes }}  
