name: Advance get artifacts
on: [workflow_dispatch]
jobs:
  get-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: List Artifacts
        run: |
          OWNER="ZePuMedical"
          REPO="imsonicSWUpgraded"
          TOKEN="${{ secrets.PAT }}"
          curl -sH "Authorization: token ${TOKEN}" \
            "https://api.github.com/repos/${OWNER}/${REPO}/actions/artifacts?per_page=100" \
            -o artifacts.json
          ARTIFACTS=$(jq -c '[.artifacts[] | {name: .name, id: .id}]' artifacts.json)
          echo "::set-output name=artifacts::$ARTIFACTS"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
