name: Get Tags
on:
  workflow_dispatch:

jobs:
  gettags:
    runs-on: ubunut-latest 

    steps:
  
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get Previous Tag
      run: |
        PREV_TAG=$(git describe --abbrev=0 --tags "${{ github.ref }}^")
        echo "::set-env name=baseRef::$PREV_TAG"
          
    - name: Set output
      id: vars
      shell: cmd
      run: echo ${{ github.ref_name }}
      
    - name: Check output
      env:
        RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
      run: |
         echo "Tag name from GITHUB_REF_NAME: ${{ github.ref }}
         echo "Tag name from github.ref_name: ${{  github.ref_name }}"

