name: Get release notes
on:
  workflow_dispatch:
    inputs:
      tagName:
        type: string
        description: 'Version'
        default: '1.0.0.1'
        
jobs:
  get-release-notes:
    runs-on: windows-latest
    steps:
      - name: Checkout Mt.BakerSystem
        uses: actions/checkout@v3
        with:
          fetch-tags: 'true'
      - name: test
        shell: cmd
        run: |
          echo ${{ github.ref }}
          echo ${{ github.ref_name }}

      - name: Create tag
        uses: joutvhu/create-tag@v1
        with:
          tag_name: v${{ github.event.inputs.tagName }}
          on_tag_exists: update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Generate Release Notes
        id: notes
        uses: RedCrafter07/release-notes-action@v1.0.0
        with:
          tag-name: v${{ github.event.inputs.tagName }}
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
      - name: Do something
        run: echo ${{ steps.notes.outputs.release-notes }}

      - name: Save release notes
        id: generate_notes
        run: |
          echo "Version: 1.1.1.1" > release_notes.txt
          echo "Date: 1/1/2023" >> release_notes.txt
          echo ${{ steps.notes.outputs.release-notes }} >> release_notes.txt

      - name: Create build artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          path: release_notes.txt
        
      - name: Display release notes
        run: |
          Get-Content release_notes.txt
