name: Get artifact name
on:
  workflow_dispatch:

jobs:
  get_artifact_name:
    runs-on: windows-2019
    steps:
      - name: Get latest artifact name
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          $ARTIFACT = curl --silent -H "Authorization: token $PAT" https://api.github.com/repos/ZePuMedical/imsonicSWUpgraded/actions/artifacts | jq -r '.artifacts[0].name'
          echo "Latest artifact name: $ARTIFACT"
          echo "artifact_name=$ARTIFACT" >> $GITHUB_ENV
