name: Get artifact name
on:
  workflow_dispatch:

jobs:
  get_artifact_name:
    runs-on: windows-2019
    steps:
      - name: Get latest artifact name
        run: |
          curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.PAT }}"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/tomasbkk/testrepo/actions/variables \
          -d '{"name":"newTestVar","value":"new test value"}'

