name: Update Artifacts List
on:
  repository_dispatch:
    types: [ "update-artifacts" ]
  workflow_dispatch:

jobs:
  update-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: List Artifacts
        id: list-artifacts
        run: |
          OWNER="ZePuMedical"
          REPO="imsonicSWUpgraded"
          TOKEN="${{ secrets.PAT }}"
          ARTIFACTS=$(curl -sH "Authorization: token ${TOKEN}" \
            "https://api.github.com/repos/${OWNER}/${REPO}/actions/artifacts?per_page=100" | jq -c '.artifacts[] | {name: .name, url: .archive_download_url, created_at: .created_at}')

          echo "$ARTIFACTS"
