name: List Artifacts
on:
  workflow_dispatch:

jobs:
  list-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: List Artifacts
        run: |
          OWNER="ZePuMedical"
          REPO="imsonicSWUpgraded"
          RUN_ID="${{ github.event.workflow_run.id }}"
          TOKEN="${{ secrets.PAT }}"
          ARTIFACTS=$(curl -sH "Authorization: token ${TOKEN}" \
            "https://api.github.com/repos/${OWNER}/${REPO}/actions/runs/${RUN_ID}/artifacts" \
            | jq -r '.artifacts[]')
          echo "Artifacts: $ARTIFACTS"
