name: Get release notes
on:
  workflow_dispatch:

jobs:
  list-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: get release notes
        run: |
          OWNER="ImSonicZePu"
          REPO="MtBakerSystem"
          TOKEN="${{ secrets.PAT }}"
          ARTIFACTS=$(curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: token ${{ secrets.PAT }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/OWNER/REPO/releases/generate-notes \
                -d '{"tag_name":"v0.9.2.3_dev_2023.09.08-10.35.17"}')
          echo -e "Release notes:\n\n$ARTIFACTS"
