name: List Artifacts
on:
  workflow_dispatch:

jobs:
  list-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: List Artifacts
        run: |
          OWNER="ZePuMedical"
          REPO="imsonicSWUpgraded"
          RUN_ID="${{ github.event.workflow_run.id }}"
          TOKEN="${{ secrets.PAT }}"
          ARTIFACTS=$(curl -sH "Authorization: token ${TOKEN}" \
              "https://api.github.com/repos/${OWNER}/${REPO}/actions/artifacts" \
              | jq -r '.artifacts[] | {name, size_in_bytes, expires_at, "workflow_run.head_branch": .workflow_run.head_branch}')
          echo "Artifacts: $ARTIFACTS"
