name: Get timestamp

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Get timestamp
      id: time
      uses: tomasbkk/get-time-action@test3
      with:
        format: 'YYYY.MM.DD-HH.mm.ss'
