name: Get timestamp

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-2019

    steps:
    
    - name: Get timestamp
      id: time
      uses: tomasbkk/get-time-action@v1.2
      with:
        format: 'YYYY.MM.DD-HH.mm.ss'
        
    - name: Print timestamp
      run: |
        echo ${{ steps.time.outputs.time }}
