name: Set repository variable
on:
  workflow_dispatch:
# variable must already exists to be updated, otherwise must use -X POST without /NAME.
jobs:
  list-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: set repository var
        run: |
          OWNER="ZePuMedical"
          REPO="imsonicSWUpgraded"
          TOKEN="${{ secrets.PAT }}"
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${TOKEN}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${OWNER}/${REPO}/actions/variables \
            -d '{"name":"MYTESTVARIABLE","value":"new test value. added another update to it."}'
          curl \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${TOKEN}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/${OWNER}/${REPO}/actions/variables \
            -d '{"name":"MYTESTVARIABLE","value":"new test value. added another update to it."}'
