name: Set repository variable
on:
  workflow_dispatch:
jobs:
  list-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: set repository var
        run: |
          OWNER="ZePuMedical"
          REPO="imsonicSWUpgraded"
          TOKEN="${{ secrets.PAT }}"
          VARNAME="MYTESTVARIABLE"
          VARVALUE="varriable value 222"
          curl \
            -X DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${TOKEN}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${OWNER}/${REPO}/actions/variables/${VARNAME}
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${TOKEN}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${OWNER}/${REPO}/actions/variables \
            -d '{"name":"${VARNAME}","value":"${VARVALUE}"}'

