name: Uprev vesion

on:
  workflow_dispatch:
    inputs:
      versionUprev:
        type: choice
        description: 'Version uprev'
        default: major
        options: 
        - major
        - feature
        - bug
        - alpha
        - beta
        - rc        

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  GITHUB_BUILD_NUMBER: ''

jobs:
  build:
    runs-on: windows-2019

    steps:

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Overwrite file
        uses: "DamianReeves/write-file-action@master"
        with:
          path: TestApp/version.txt
          write-mode: overwrite
          contents: |
            console.log('some contents')
            
      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true
          message: 'Overwritten by Github Actions - ${date}'
