name: Uprev vesion

on:
  push:
    branches: 
      - master
  workflow_dispatch:
    inputs:
      versionUprev:
        type: choice
        description: 'Version uprev (only for master branch)'
        default: rev
        options: 
        - major
        - minor
        - patch
        - rev
        - none

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  GITHUB_BUILD_NUMBER: ''
  RUN_ALL_STEPS: 1

jobs:
  build:
    runs-on: windows-2019

    steps:
    
      - name: Set release build details
        if: ${{ env.RUN_ALL_STEPS == 1 }}
        run: |
          echo "BUILD_DETAILS=" >> $env:GITHUB_ENV
        
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Uprev version
        if: ${{ env.RUN_ALL_STEPS == 1 && github.event.inputs.versionUprev != 'none' && github.ref_name == 'master' }}
        shell: cmd
        run: |
          echo ${{ env.BUILD_DETAILS }}
          ${{ github.workspace }}/TestApp/uprev.bat ${{ github.workspace }}/TestApp ${{ github.event.inputs.versionUprev }}
            
      - name: Commit & Push
        if: ${{ env.RUN_ALL_STEPS == 1 && github.event.inputs.versionUprev != 'none' && github.ref_name == 'master' }}
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true
          message: 'Comitted and pushed version.txt'
