name: Uprev vesion

on:
  workflow_dispatch:
    inputs:
      versionUprev:
        type: choice
        description: 'Version uprev'
        default: rev
        options: 
        - major
        - minor
        - patch
        - rev
        - none

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  GITHUB_BUILD_NUMBER: ''

jobs:
  build:
    runs-on: windows-2019

    steps:

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Uprev version
        if: ${{ env.RUN_ALL_STEPS == 1 && github.event.inputs.versionUprev != 'none'}}
        shell: cmd
        run: ${{ github.workspace }}/TestApp/uprev.bat ${{ github.event.inputs.versionUprev }}
            
      - name: Commit & Push
        if: ${{ env.RUN_ALL_STEPS == 1 && github.event.inputs.versionUprev != 'none'}}
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true
          message: 'Comitted and pushed version.txt'
